# Generated by Django 4.0.2 on 2022-02-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
