# Generated by Django 4.0.2 on 2022-02-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perpustakaan', '0003_kelompok_buku_kelompok_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='buku',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
